import java.util.Arrays;

global com.app.brpm.model.ProductDetails productDetails;
dialect  "mvel"

rule "generate a packing slip for shipping"
    when
        ProductDetails(type.equalsIgnoreCase("physical product"));
    then
        productDetails.setActions(Arrays.asList("generate a packing slip for shipping", "generate a commission payment to the agent"));
end

rule "create a duplicate packing slip for the royalty department"
    when
        ProductDetails(type.equalsIgnoreCase("book"));
    then
        productDetails.setActions(Arrays.asList("create duplicate parking slip for the royalty department",
         "generate a commission payment to the agent"));
end